server:
  port: 8080 # 访问端口
  servlet:
    context-path: / # 访问根路径
    session:
      timeout: PT30M # session超时为30分钟
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource: # 数据库配置
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ddp?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis: # Redis相关配置内容
    host: 123.207.205.232 # Redis 服务器地址
    port: 6379 # Redis 服务器端口
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-idle: 8 # 连接池中的最大空闲连接 默认 8
      min-idle: 0 # 连接池中的最小空闲连接 默认 0
    timeout: 0 # 关闭时长
  session:
    store-type: redis # 使用Redis方式存储Session

mybatis: # Mybatis 配置
  mapper-locations: classpath:mapper/*.xml #定义xml文件位置，不是必须的，如果需要在xml写sql请配置此选项
  type-aliases-package: ddp.entity # 注意：对应实体类的路径
mapper: # 通用Mapper配置
  mappers:  ddp.MyMapper  # 通用Mapper
  identity: MYSQL
pagehelper: # 分页配置
  helper-dialect: mysql # 指定数据库，可以不配置，pagehelper插件会自动检测数据库的类型
  reasonable: true # 分页合理化参数默认false，当该参数设置为true 时，pageNum <= 0 时，默认显示第一页，pageNum 超过 pageSize 时，显示最后一页
  support-methods-arguments: true # 分页插件会根据查询方法的参数中，自动根据params 配置的字段中取值，找到合适的值会自动分页
  params: count=countSql # 用于从对象中根据属性名取值，可以配置pageNum，pageSize，count 不用配置映射的默认值

logging:
  config: classpath:logback-spring.xml
  file:
    path: G:\usr\java\ddp-web-server
